import create from "zustand";

export const useStore = create((set) => ({
	selectedTool: "",
	selectedMode: "",
	selectedRatio: new Set(["original"]),
	selectedCropMode: "",
	isDroppedPhoto: false,
	imgUrl: undefined,
	imgDim: [0, 0],
	imgDimOriginal: [0, 0],
	scale: 0.5,
	exposure: 1,
	saturation: 1,
	contrast: 1,
	brightness: 1,
	red: 1,
	green: 1,
	blue: 1,
	blur: 0,
	zoom: 1,
	resetSnap: false,
	setSelectedTool: (value) => set((state) => ({ selectedTool: value })),
	setSelectedMode: (value) => set((state) => ({ selectedMode: value })),
	setSelectedRatio: (value) => set((state) => ({ selectedRatio: value })),
	setSelectedCropMode: (value) =>
		set((state) => ({ selectedCropMode: value })),

	dropPhotoUpdate: () =>
		set((state) => ({ isDroppedPhoto: !state.isDroppedPhoto })),
	setImgUrl: (url) => set((state) => ({ imgUrl: url })),
	setImgDim: (dim) => set((state) => ({ imgDim: dim })),
	setImgDimOriginal: (dim) => set((state) => ({ imgDimOriginal: dim })),
	setExposure: (value) => set((state) => ({ exposure: value })),
	setRed: (value) => set((state) => ({ red: value })),
	setGreen: (value) => set((state) => ({ green: value })),
	setBlue: (value) => set((state) => ({ blue: value })),
	setSaturation: (value) => set((state) => ({ saturation: value })),
	setContrast: (value) => set((state) => ({ contrast: value })),
	setBrightness: (value) => set((state) => ({ brightness: value })),
	setBlur: (value) => set((state) => ({ blur: value })),
	setZoomIn: () => set((state) => ({ zoom: state.zoom + 0.1 })),
	setZoomOut: () => set((state) => ({ zoom: state.zoom - 0.1 })),
	setZoom: (value) => set((state) => ({ zoom: value })),

	setResetSnapFalse: () => set((state) => ({ resetSnap: false })),
	setResetSnapTrue: () => set((state) => ({ resetSnap: true })),
	setScale: (scale) => set((state) => ({ scale: scale })),

	setReset: () =>
		set((state) => ({
			blur: 0,
			contrast: 1,
			exposure: 1,
			saturation: 1,
			brightness: 1,
			red: 1,
			green: 1,
			blue: 1,
			zoom: 1,
			imgDim: [state.imgDimOriginal[0], state.imgDimOriginal[1]],
			selectedRatio: new Set(["original"]),
		})),
}));
